### ISSUE TITLE
提交一个自己的python个人微信号api项目

### ISSUE THREAD

**Issue by littlecodersh** [fritx/awesome-wechat#1]
**Info**

[LittleCoder/itchat][itchat_code]: (个人号) (SDK) 微信个人号接口，三十行即可自定义个人号机器人。

**Raw**

```markdown
[LittleCoder/itchat][itchat_code]: (个人号) (SDK) 微信个人号接口，三十行即可自定义个人号机器人。

[itchat_code]: https://github.com/littlecodersh/ItChat
```

[itchat_code]: https://github.com/littlecodersh/ItChat

**Comment by fritx** [comment]
@littlecodersh 多谢分享
